version: '2'
services:
  novnc:  
    image: realjc/msckf-vio:v3
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "8080:8080"
    networks:
      - x11
    volumes:
      # mount your workspace here:
      - ~/Documents/Euroc:/data
networks:
  x11:
