version: '3.4'
services:
  # cpu development:
  env_for_loam:
    # build:
    #   context: docker
    #   dockerfile: Dockerfile
    #   network: host
    image: realjc/loam_env:v1
    container_name: env_for_loam
    privileged: true
    # environment:
    #     # set VNC login password here:
    #     - VNC_PASSWORD=sensorfusion
    # volumes:
    #   # mount your workspace here:
    #   - $PWD/workspace:/workspace
    ports:
      # HTML5 VNC:
      - 40080:80
      # standard VNC client:
      - 45901:5901
      # supervisord admin:
      - 49001:9001
      # # ROS master:
      # - 11311:11311